# Generated by Django 4.2.3 on 2024-06-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reset_token',
        ),
    ]
