# Generated by Django 4.2.3 on 2024-06-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
